#Install OpenSCAP 
---

- hosts: all
  vars:
    oscap_profile: xccdf_org.ssgproject.content_profile_stig-rhel7-disa
    oscap_policy: stig-rhel7-disa

  tasks:
  - name: install openscap scanner
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - openscap-scanner
    - scap-security-guide

  - block:
    - name: run openscap
      command: oscap xccdf eval \
        --profile {{ oscap_profile }} \
        --results-arf /tmp/oscap-arf.xml \
        --report /tmp/oscap-report.html \
        --fetch-remote-resources \
        /usr/share/xml/scap/stig/content/{{ oscap_policy }}.xml

    always:
    - name: download report
      fetch:
        src: /tmp/oscap-report.html
        dest: ../oscap-reports/{{ inventory_hostname }}.html
        flat: yes
